### ISSUE TITLE
Beginning of game logic error

### ISSUE THREAD

**Issue by PeterEFrancis** [tneller/gin-rummy-eaai#2]
On line [113](https://github.com/tneller/gin-rummy-eaai/blob/a6de576f12d9daa12d95eec1a51508ba4e0dfa59/GinRummyGame.java#L113) of `GinRummyGame.java`, it is enforced that if the number of turns taken is 3 and the face-up card is the first face-up card, then the first player must draw the face-down card. This is intended to capture the rule that if both players decline the first face-up card, the first player must draw face-down, but does not, and there is another situation that this line applies to, but should not. The following table whose lines show successive turns, summarizes:

| Player 0 hand | Player 1 hand | Face-up stack | move |
|:----:|:----:|:---|:----|
| A ... | B ...  | C   | 
| C ... | B ... | A    | player 0 draws C and discards A |
| C ... | A ... | B    | player 1 draws A and discards B |
| B ... | A ... | C    | player 0 draws B and discards C |

Now the number of turns taken is three and the face-up card is C (the first face-up card); Player 1 is forced to take the face-down card, but should be allowed to take C.

Player 0 only plays on even turn numbers; the easiest fix would be to change `turnsTaken == 3` to `turnsTaken == 2`.

**Comment by tneller** [comment]
Change accepted.
