### ISSUE TITLE
Unused methods in the GinRummyPlayer interface

### ISSUE THREAD

**Issue by stevenbogaerts** [tneller/gin-rummy-eaai#3]
In the GinRummyPlayer interface, there are two methods (reportLayoff and reportFinalHand) that are not currently called within the GinRummyGame class. Are these deprecated? May we ignore them?

**Comment by tneller** [comment]
Proposed implementation of reportLayoff:
`							if (layOffCard != null) {
								if (playVerbose)
									System.out.printf("Player %d lays off %s on %s.\n", opponent, layOffCard, layOffMeld);
								for (int i = 0; i < 2; i++) 
									players[i].reportLayoff(opponent, layOffCard, layOffMeld);
								unmeldedCards.remove(layOffCard);
								layOffMeld.add(layOffCard);
								cardWasLaidOff = true;
								break;
							}`

**Comment by tneller** [comment]
Proposed implementation of reportFinalHand:

```
			// report final hands
			for (int i = 0; i < 2; i++)
				for (int j = 0; j < 2; j++)
					players[i].reportFinalHand(j, (ArrayList<Card>) hands.get(j).clone());
```
