### ISSUE TITLE
Put the code in a package?

### ISSUE THREAD

**Issue by stevenbogaerts** [tneller/gin-rummy-eaai#5]
Could the given code be put in an explicit package (rather than the default package)? "package ginrummy;" or something like that. This would enable the defining of other packages for organizing other code.

**Comment by tneller** [comment]
Other packages can be defined regardless of whether this is in the default package or not.  Given that other teams have been implementing using the default package, packaging these few classes would create more revision work for teams than it would save.   In future contest, we would like start with a package.  Thank you for the feedback.
